FROM rradev/minkowski-engine:latest 

RUN pip install timm tensorboardx einops pytorch-lightning LarpixParser wandb

CMD ["bash"]

# the minkowski latest uses the dockerfile defined here https://gist.github.com/radiradev/7af53500133773948c813d3e133e62c8
