FROM rradev/minkowski:torch1.12_final

RUN pip install tensorboardx einops LarpixParser wandb 
RUN pip install pytorch-lightning timm --no-deps
CMD ["bash"]

# the minkowski latest uses the dockerfile defined here https://gist.github.com/radiradev/7af53500133773948c813d3e133e62c8
