data:
  data_path: /global/cfs/cdirs/dune/users/rradev/contrastive/individual_particles/larndsim_throws_converted
clr_features_path: /pscratch/sd/r/rradev/converted_data/clr_features
wandb_tmp_dir: /pscratch/sd/r/rradev/wandb
checkpoint_dirpath: /pscratch/sd/r/rradev/contrastive_neutrino_ckpt