data:
  # data_path: /pscratch/sd/r/rradev/larndsim_throws_converted_new
  nominal_data_path: /share/rcifdata/awilkins/contrastive-neutrino_data/training_data/nominal/larndsim_throws_converted_nominal
  # throws: /global/cfs/cdirs/dune/users/rradev/contrastive/edep_2thousand_per_particle/
  electronics_throws: /share/rcifdata/awilkins/contrastive-neutrino_data/training_data/electronics/larndsim_converted/
# throws:
#   throw15: all_nominal
#   throw1: all_pos_max
#   throw2: all_pos_min
#   throw3: efield_pos_max
#   throw4: transdiff_pos_max
#   throw5: lifetime_pos_max
#   throw6: efield_neg_max
#   throw7: transdiff_neg_max
#   throw8: lifetime_neg_max
#   throw9: all_0.25_pos_max
#   throw10: all_0.25_neg_max
#   throw11: all_0.50_pos_max
#   throw12: all_0.50_neg_max
#   throw13: all_0.75_pos_max
#   throw14: all_0.75_neg_max
#   throw17: all_3xneg_max

electronics_throws:
  nominal: nominal
  throw1: throw1
  throw2: throw2
  throw3: throw3
  throw4: throw4
  throw5: throw5
  throw6: throw6
  throw7: throw7
  throw8: throw8
  throw9: throw9
  throw10: throw10

# clr_features_path: /pscratch/sd/r/rradev/converted_data/clr_features
wandb_tmp_dir: /home/awilkins/contrastive-neutrino/wandb
checkpoint_dirpath: /home/awilkins/contrastive-neutrino/ckpts
