model_type: single_particle_classfier

data:
  data_path: /pscratch/sd/r/rradev/converted_data/train
  workspace: /global/u1/r/rradev/contrastive-neutrino

wandb_tmp_dir: /pscratch/sd/r/rradev/wandb
checkpoint_dirpath: /pscratch/sd/r/rradev/contrastive_neutrino_ckpt