data:
  data_path: /pscratch/sd/r/rradev/larndsim_throws_converted_new
  protons_only: /global/cfs/cdirs/dune/users/rradev/contrastive/edep_2thousand_per_particle/larndsim_converted
  all_max: /global/cfs/cdirs/dune/users/rradev/contrastive/edep_2thousand_per_particle/all_positive_max/larndsim_converted/
clr_features_path: /pscratch/sd/r/rradev/converted_data/clr_features
wandb_tmp_dir: /pscratch/sd/r/rradev/wandb
checkpoint_dirpath: /pscratch/sd/r/rradev/contrastive_neutrino_ckpt