data:
  data_path: /pscratch/sd/r/rradev/converted_data/train
clr_features_path: /pscratch/sd/r/rradev/converted_data/clr_features
wandb_tmp_dir: /pscratch/sd/r/rradev/wandb
checkpoint_dirpath: /pscratch/sd/r/rradev/contrastive_neutrino_ckpt