data_path: /pscratch/sd/r/rradev/larndsim_throws_converted_nominal

train_dataset:
  train_mode: True
  _target_: data.dataset.ClassifierAugmentedDataset
  root: ${data_path}/train/

val_dataset:
  train_mode: False
  _target_: data.dataset.ClassifierAugmentedDataset
  root: ${data_path}/val/


num_of_gpus: 1
limit_train_batches: 1.0
batch_size: 256

model: 
  _target_: modules.classifier.Classifier
  batch_size: ${batch_size}

collate_fn:
  _target_: MinkowskiEngine.utils.batch_sparse_collate
  _partial_: True

wandb_checkpoint: 0

run_name: classifier_augmented


